### ISSUE TITLE
Multiple Govee Floodlights show up as single light

### ISSUE THREAD

**Issue by rb2k** [wez/govee-lan-hass#12]
I just bought the Govee Floodlights.
First of all: thanks for the work, nice setup experience!

The floodlight model numbers are H7062(6PACK) & H7060(4PACK) & H7061(2PACK).
On Amazon you can see them here: https://www.amazon.com/Govee-Outdoor-Changing-2700-6500K-Waterproof/dp/B09FXH4YLG

On the Govee app, you can select specific lights and control their color.
In the homeassistant integration I just see the 4 lights as a single device.

Is that a limitation on the Govee API or something that isn't implemented yet?

**Comment by wez** [comment]
The LAN and HTTP APIs just give simple overall control of power/brightness/color.  Individual light control is not part of any of their officially documented API surface. It's possible to sniff the BLE traffic from the govee app and add support for individual segments if you are motivated and have it in range of your home assistant's bluetooth device, or an esphome bluetooth proxy!

**Comment by rb2k** [comment]
Thanks, that's what I assumed :)

**Comment by wez** [comment]
I have no plans to fix this here in this integration, but I do want to note that my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) is where I will be adding support for controlling segments, so you may wish to consider moving to that.
