### ISSUE TITLE
Support for Appliances

### ISSUE THREAD

**Issue by KyleStilkey** [wez/govee-lan-hass#14]
I was wondering if you would be able to add the supported appliances that Govee has released with their 2.0 API?

If these could be added and supported I do own many of the listed devices and can be willing to help.
https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf

I've been slowly adding them manually as scripts and templates but I think it would be easier as a supported integration.

Thanks!

**Comment by wez** [comment]
I don't own any govee appliances, so it will be awkward for me to get the ball rolling, but I'm open to helping you figure out it out if you're up for having a go and submitting some pull requests!

First, https://github.com/wez/govee-py needs to be taught to understand appliances. A basic first-pass at that might be to look at https://github.com/wez/govee-py/blob/main/govee_led_wez/http.py and adjust the functions in there to accept an optional `appliance` boolean parameter to use the appliance part of the api.  I think that `GoveeHttpDeviceDefinition` should probably have an `appliance` boolean field to indicate that it is an appliance, assuming that the same device doesn't show up as both a light and an appliance.  That will be important for making requests to the correct URL based on the type of the device.

Second, I think `GoveeController` will need a `set_mode` method, similar to `set_power_state` (https://github.com/wez/govee-py/blob/main/govee_led_wez/govee.py#L398) but for use in setting the appliance mode via the `/v1/appliance/devices/control ` endpoint.

Then for the home assistant integration, I think there could be a lot of questions depending on which home assistant "platform" best matches it.  I don't have a good sense for this at the moment. https://developers.home-assistant.io/docs/creating_platform_index discusses platforms; I'd suggest that you skim that and see which of your appliances best match to the platforms listed there.

The control capabilities of the HTTP appliance API seem like they map to power on/off and presets of some kind.  The power state could map to a simple switch (https://developers.home-assistant.io/docs/core/entity/switch).  I know that lights have a preset concept, but I'm not sure about switches.  Maybe it's "OK" to map appliances to lights, so long as they don't report fancy color or dimming features? That might be the easiest thing to code.

Once you have a sense of that, it's then a matter of coding it up!

**Comment by KyleStilkey** [comment]
I'll take a look I am not very good but am in the works trying to just come up with a simple solution others have as well, but this is what got me trying and thinking about it.

https://community.home-assistant.io/t/govee-appliances-heaters-fans-purifiers/520678

We can call the API and make ON/OFF, Modes and speeds from the devices I have that are supported (Air purifiers, fans and humidifiers.)

I am not the greatest when it comes to this stuff, but I can try and help, I also can provide you with the call back I got from the API for codes, requests and commands and such if that will help you as well.

**Comment by KyleStilkey** [comment]
Yeah I am at a loss on what to do exactly or how to create it to look for appliances vs light, but they do have different call URLs and I could provide you with any data needed from my devices and assis where I can.

**Comment by KyleStilkey** [comment]
> Hey, if you all are still working on this I got my Govee smart kettle and would be willing to help out.

Sadly this isn't in the Govee API calls so it won't be possible unless they add to it and sadly I'm not good enough to code very well that I hope someone might be able to come and make this addition some day.

**Comment by mprobber** [comment]
Howdy!
@wez thank you for your work on this HACs integration.  I'd like to take a stab at building support for the appliance API in `govee-py`, but I'm rather new to asyncio as I haven't worked in Python in quite a few years.

I tried to get `govee-py` just to query the API so I could start working, but when I follow the "Getting Started" script, I get the following error

```
Traceback (most recent call last):
  File "/home/mike/code/govee-py/test.py", line 14, in <module>
    controller.start_http_poller()
  File "/home/mike/code/govee-py/govee_led_wez/govee.py", line 154, in start_http_poller
    self.http_poller = asyncio.create_task(self._http_poller(interval))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 371, in create_task
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'GoveeController._http_poller' was never awaited
```
```

**Comment by wez** [comment]
@mprobber I'm not an expert on python's asyncio, so I'd suggest looking at the hello world example over here: https://docs.python.org/3/library/asyncio.html

**Comment by wez** [comment]
I have no plans to work on that here in this integration, but I do want to note my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) is where I'm focusing my efforts and either this device already works there, or is easier to add support for over there, so you may wish to consider moving to that.
