### ISSUE TITLE
Light strips turns on every ten minutes

### ISSUE THREAD

**Issue by adam-cobb** [wez/govee-lan-hass#16]
One of my light strips (a H6159) turns on every ten minutes without any interaction or trigger from myself. When I look at logs it is precisely every ten minutes and has been doing it for the last few days. I'm not sure if this is related to the http status check (as I believe that's every 10 minutes?) But I don't seem to be able to stop it (tried restarting the integration and HA).

I have another H6159 light strip and that seems fine and doesn't turn on by itself.

I also enables debugging logging but that doesn't appear to tell me much other than the status changes to on at those ten minutes intervals

**Comment by adam-cobb** [comment]
Thanks. I don't have any other automations running elsewhere and it definitely wasn't anything in HA itself (logs show it being turned on externally from HA). All I can do is try the power cycle as you suggest. Know what you mean about it being frustrating there's not a lot to go on, but thanks for replying anyway.

**Comment by wez** [comment]
I'm going to close this as there isn't a lot to go on and no one else has reported anything similar!
