### ISSUE TITLE
govee strips disconnecting when wifi goes out

### ISSUE THREAD

**Issue by Adaaks** [wez/govee-lan-hass#19]
i have govee lan control for my strips, but when the wifi goes out, the strips also disconnect and do not work anymore until i re-add them. please fix this

**Comment by wez** [comment]
First, I don't like the tone of your post; coupled with its brevity, it comes across as rude and a bit entitled.

Second: there's not a lot to go on here. You need to help me to help you.

Read through https://github.com/wez/govee-lan-hass#notes and then work through https://github.com/wez/govee-lan-hass#troubleshooting and share what you find.

**Comment by Adaaks** [comment]
i dont know too, the strips just go unavailable bascially every day. i have to restart home assistant for it to work again. maybe you could  make a check to see if the govee led strips are unavailable, and make it available again please.

i tried doing the logs thing but i just got a shit ton of info, and 3 thousand words that match govee, so i dont think i can see the exact issue.

**Comment by Adaaks** [comment]
this might be useful

2023-05-08 22:32:09.578 DEBUG (MainThread) [custom_components.govee_lan.light] timeout while querying device state for E4:26:D4:AD:FC:49:F8:68 light.strips
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/govee_lan/light.py", line 420, in async_update
    await self._govee_controller.update_device_state(self._govee_device)
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 287, in update_device_state
    await asyncio.wait_for(future, timeout=self.device_control_timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by wez** [comment]
Potentially the same cause as https://github.com/wez/govee-lan-hass/issues/13

There's still not enough information in your report for me to help you figure this out.

In that other issue, folks dug in to examine what was happening on their network and we fixed an issue on multi-homed systems (those that have multiple IP addresses).

**Comment by Adaaks** [comment]
thanks for the reply, doesnt seem to be the issue mentioned. i guess i will just have to deal with it.

**Comment by wez** [comment]
Alrighty; I'll close this, but if you find out more information, please reopen and share that information.
