### ISSUE TITLE
Govee Scene ?

### ISSUE THREAD

**Issue by schumi2309** [wez/govee-lan-hass#2]
Hello,
Is it possible to recover the scenes of the govee application in Home assistant?
We can change the colors, but I would have liked to be able to put scenes like lightning etc...
is this possible?

Thanks...

**Comment by wez** [comment]
Not via the LAN API, but it is technically possible via BLE, provided that someone has sniffed the BLE packets sent by the app for the device and we've figured out what the packets mean. 
I have some uncommitted work in progress for this for some of my devices.
It is compatible with hass bluetooth proxies.

See also: https://github.com/egold555/Govee-Reverse-Engineering

**Comment by schumi2309** [comment]
Thank you for the info. And what a pity...
I looked at the list but none are there. Here are mine:

![Capture d’écran 2022-12-20 à 15 49 06](https://user-images.githubusercontent.com/47976917/208695049-d27ce791-61a5-4813-bd16-88fe54506704.png)

**Comment by snipestyle9410** [comment]
I think this must be possible in some way. Currently it is possible to trigger scenes via Alexa. In the Govee-App you can define "Tap-to-run" Commands. Those will become available in the Alexa App as a scene. At this point you can trigger those scene

**Comment by wez** [comment]
There isn't a documented or supported way to do this via the LAN control API.

The author of https://github.com/bwp91/homebridge-govee has invested time in reverse engineering the undocumented and unsupported commands used by the Alexa integration, but they are high effort to maintain and I don't personally have the need for that, and certainly don't have the time for that here.

**Comment by fleshinachair** [comment]
> I think this must be possible in some way. Currently it is possible to trigger scenes via Alexa. In the Govee-App you can define "Tap-to-run" Commands. Those will become available in the Alexa App as a scene. At this point you can trigger those scene

Does this mean in home assistant we can just setup a switch that will silently fire the command off to Alexa and trigger the scene?

**Comment by snipestyle9410** [comment]
> 

Yes. This is what i am doing at the moment. Unfortunately there is some delay, because you are telling homeassistant to tell alexa to trigger a scene and alexa is telling the govee application to set the scene. I think you got the point. This process takes some time, but is the only way to set a scene via HA.

**Comment by bwp91** [comment]
The scene codes in fact do work via the Govee LAN API (just don't seem to be documented)

**Comment by smarthomeaf** [comment]
+1  THis would be great!

**Comment by brwyatt** [comment]
I assume making the calls to Govee is the easy part, but getting this to show up on Home Assistant in a way that's usable is the trickier part?

Really good to see this in their HTTP API, finally. Hopefully that means it'll show up in their LAN API at some point in the near future, too.

**Comment by wez** [comment]
I've been working on the successor to `govee-lan-hass` which is `govee2mqtt`, a service that bridges your govee devices into home assistant via MQTT.  It also happens to support the new scene API.

Learn more about it here: https://github.com/wez/govee2mqtt#govee-to-mqtt-bridge-for-home-assistant


![image](https://github.com/wez/govee-lan-hass/assets/117777/261ebf34-ae3c-443a-9d01-f5c85a1dcdfb)

![image](https://github.com/wez/govee-lan-hass/assets/117777/5372d4d1-bfcc-4d3e-a583-40de018b6333)

**Comment by schumi2309** [comment]
very good news.
When could we test this?

**Comment by wez** [comment]
If you are running HAOS or Supervised HASS, then follow the steps here: https://github.com/wez/govee-lan-hass/issues/50#issuecomment-1876104679
If you have a machine on your network that runs docker, then: https://github.com/wez/govee2mqtt/blob/main/DOCKER.md

**Comment by wez** [comment]
I'm going to close this in favor of my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt), which supports this feature.
