### ISSUE TITLE
After updating govee lan, unrecognized devices

### ISSUE THREAD

**Issue by GuidoTraversari** [wez/govee-lan-hass#20]
Good morning to all
after updating Goove Lan integration, my 2 devices (2 led lights) stopped working. The integration can no longer find them in my network. i have tried uninstalling the integration and reinstalling it but the problem remains. i have also requested the Goove app to send back a new key Api, but despite this nothing has changed. the devices i have in lan are gone and the integration can no longer see them. what to do now?

Logger: custom_components.govee_lan.light
Source: custom_components/govee_lan/light.py:150
Integration: Govee LAN Control ([documentation](https://github.com/wez/govee-lan-hass), [issues](https://github.com/wez/govee-lan-hass/issues))
First occurred: 14:04:22 (3 occurrences)
Last logged: 19:05:38

failed to get device list from Govee HTTP API. Will retry in the background
Traceback (most recent call last):
  File "/config/custom_components/govee_lan/light.py", line 150, in async_setup_entry
    await controller.query_http_devices()
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 228, in query_http_devices
    devices = await http_get_devices(self.api_key)
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/http.py", line 66, in http_get_devices
    raise RuntimeError(f"failed to get devices: {message}")
RuntimeError: failed to get devices: rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time.

**Comment by wez** [comment]
Looks like you've exhausted you API limit with the HTTP API.

If you delete the govee lan integration and re-add it, but leave the HTTP API key blank you should be able to run in LAN-only mode.

Note that the device ids/names won't be "as good" as those we can get when using the HTTP API, but you can rename them as you see fit once they are detected.
