### ISSUE TITLE
Add Govee RGBIC (H6127) BLE Support

### ISSUE THREAD

**Issue by Prash1407** [wez/govee-lan-hass#21]
Hi Wez,

Unfortunately, I cannot seem to find my BLE Govee using your tool, and it does not support LAN API through the app.

However, I found some resources of reverse engineering for this Govee RGB IC module, would you be able to implement the function using these resources?

https://pypi.org/project/govee-api-ble/
https://github.com/BeauJBurroughs/Govee-H6127-Reverse-Engineering

Really appreciate your support and amazing work you're doing as all my other Govee Lights are integrated as they Wi-Fi not BLE.

Thank you!

**Comment by wez** [comment]
Sorry, no; I don't have this device and don't want to buy one, and don't have time to spare to look into this.

You may be able to resolve this for yourself; the BLE packets seem fairly similar across the different govee devices, so you can try adding a model for your device to the underlying python library:

https://github.com/wez/govee-py/blob/main/govee_led_wez/models.py#L30

and see if you can find out which combination of settings makes it work.

If you can and do, please submit a PR to that repo!

**Comment by trostmarvin** [comment]
So does [govee-lan-hass](https://github.com/wez/govee-lan-hass) natively support BLE? 
Your linked repo says something about enabling BLE and in HA I see no settings for BL-Adapter. My light strip didn't work out of the box with this integration, but it's not in the `INFO_BY_MODEL` dictionary too.

Thanks!
