### ISSUE TITLE
Govee LAN Control failing to retrieve entities 

### ISSUE THREAD

**Issue by kevintothecore** [wez/govee-lan-hass#22]
This error originated from a custom integration.

Logger: custom_components.govee_lan.light
Source: custom_components/govee_lan/light.py:150 
Integration: Govee Lights (documentation, issues) 
First occurred: 12:55:53 PM (3 occurrences) 
Last logged: 12:57:55 PM

failed to get device list from Govee HTTP API. Will retry in the background
Traceback (most recent call last):
  File "/config/custom_components/govee_lan/light.py", line 150, in async_setup_entry
    await controller.query_http_devices()
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 228, in query_http_devices
    devices = await http_get_devices(self.api_key)
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/http.py", line 66, in http_get_devices
    raise RuntimeError(f"failed to get devices: {message}")
RuntimeError: failed to get devices: service is busy please try again later

**Comment by lukas-clarke** [comment]
This is also happening to me. I can no longer seem to enable Local Control in the app and am wondering if they are related. Can you ensure Local Control is enabled for you?

**Comment by kevintothecore** [comment]
> This is also happening to me. I can no longer seem to enable Local Control in the app and am wondering if they are related. Can you ensure Local Control is enabled for you?

Same thing for me. 
LAN Control disappeared in the Govee app.

**Comment by lukas-clarke** [comment]
The issue resolved for me without any changes. I looked at the code and the error was occuring during the govee http call. It seems like there may have been an issue on the govee server end and now it's resolved.
