### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by aerozinga** [wez/govee-lan-hass#27]
Hi, not sure how to report this. My log says the below. I am on version 2023.6.0

Entity light.mancave_strip_2 (<class 'custom_components.govee_lan.light.GoveLightEntity'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.

**Comment by wez** [comment]
This should be resolved as of 18d8455510d158496f7e5d4f0286f58bd61042bb
Thanks!
