### ISSUE TITLE
Port 4003

### ISSUE THREAD

**Issue by krispycorn** [wez/govee-lan-hass#28]
Hi,

I've been able to successfully add the addon but I don't think that I can control the lights via LAN because nothing is apparently listening on port 4003. Is there something that I have to do manually to enable the integration access to port 4003? I haven't been able to find a method or guidance on this. Thank you!

**Comment by krispycorn** [comment]
Update: I was able to enable LAN by enabling access to ports 4001, 4002, and 4003 on my server. Is this the proper way and would I possibly face any issues in the future?

**Comment by wez** [comment]
https://github.com/wez/govee-lan-hass#requirements-of-the-lan-api lists the requirements.

UDP Port 4003 is required by Govee's LAN API; it must be available for the HA machine to bind to in order to both send and receive information from the various Govee devices.

**Comment by krispycorn** [comment]
Sorry for the late response, I understand that port 4003 needs to be open, but when opening it exclusively -- it is unable to connect to be controlled.

I have to additionally open both 4001 and 4002 for the lights to work via LAN -- just wondering if this was normal.

**Comment by wez** [comment]
I recently went back and re-read the docs on this, and yes, ports 4001, 4002 and 4003 are all involved in this protocol. It's not great IMO, and I must have blocked out how horrible it is :-p
I've updated https://github.com/wez/govee-lan-hass/blob/main/README.md#requirements-of-the-lan-api with an improved discussion around the ports.
