### ISSUE TITLE
Possible interruption of connection after router reboot

### ISSUE THREAD

**Issue by VynDesign** [wez/govee-lan-hass#3]
I had to reboot my router earlier today due to some buffering during streaming media, and later discovered that my Govee H7060 outdoor floodlights had not been turned on at the appropriate time via the automation I have in Home Assistant that should have turned them on 30 mins prior to sunset. I tried turning them on manually via Home Assistant only to find that they were reporting as available, and on. Toggling the on/off toggle did not make any difference, the lights did not turn on. Switching over to the Govee Home app, they appropriately indicated that they were off, and turned on and off and on again without issue. I tried re-saving the configuration of the integration with the api-key to no avail. I later restarted Home Assistant and the devices now work properly - I can toggle them on and off via Home Assistant again. I'm wondering if there is some sort of issue with auto-recovery after a network outage or router reboot where the state of the devices/entities is not reporting properly until HA is restarted. The devices were acting as though they were 'unavailable' but were displayed as if nothing was wrong.

**Comment by wez** [comment]
I got swamped in notifications over the holidays and only just saw this.

I'd suggest adding this to your `configuration.yaml`:

```yaml
logger:
  logs:
    custom_components.govee_lan: debug
    govee_led_wez: debug
```

and then see what is logged if you reboot your router. That will help to understand what happen(s|ed) in that situation.

**Comment by VynDesign** [comment]
Cool, I will do that and test it when possible.

**Comment by jason-curtis** [comment]
I'm having a similar issue. 2 Govee lights (1 floor lamp, 1 rope light), both were set up with govee_lan_api and working fine through a HASS migration to a different box and through an upgrade to a new mesh network (Deco 6E). One day after a router reboot, I couldn't control the lights through HASS anymore. Still can't. The lights still work through the Govee app.

I turned on debug logging and did a router reboot - this showed up in the logs:

```
Logger: homeassistant.helpers.entity
Source: custom_components/govee_lan/light.py:420
Integration: Govee Lights ([documentation](https://github.com/wez/govee-lan-hass), [issues](https://github.com/wez/govee-lan-hass/issues))
First occurred: 8:57:20 PM (6 occurrences)
Last logged: 8:58:20 PM

Update for light.rope_light fails
Update for light.floor_lamp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in async_device_update
    await self.async_update()
  File "/config/custom_components/govee_lan/light.py", line 420, in async_update
    await self._govee_controller.update_device_state(self._govee_device)
  File "/usr/local/lib/python3.11/site-packages/govee_led_wez/govee.py", line 299, in update_device_state
    self._request_lan_status(device.lan_definition)
  File "/usr/local/lib/python3.11/site-packages/govee_led_wez/govee.py", line 270, in _request_lan_status
    self._send_lan_command(
  File "/usr/local/lib/python3.11/site-packages/govee_led_wez/govee.py", line 266, in _send_lan_command
    dgram_socket.bind((self.lan_source_address, 0))
OSError: [Errno 99] Address not available
```

Any ideas? I've considered removing the devices and the integration and starting over, but I figured I should see if you have any thoughts first. I've given the HASS box a static IP and I tried giving the lights static IP addresses as well, but I did that after the issue started so I didn't actually expect it to fix anything (I don't know what the IPs were originally 🤷).

**Comment by wez** [comment]
I'd strongly recommend using static IPs for both HASS and the govee devices; that way the IP can't/won't change and you won't experience issues like this

**Comment by jason-curtis** [comment]
Makes sense. Since I messed this up and don’t know what the original IPs were for the devices, is my best option to remove the devices and start over?

**Comment by wez** [comment]
the IPs are discovered automatically periodically; no need to wipe anything or start over. Just make sure they have static IPs and maybe reload the integration (or restart hass) and it should be smooth sailing from there

**Comment by jason-curtis** [comment]
I did a supervisor update and restarted hass - looks like everything is back working again!

The connection was broken for several days  though so maybe the periodic rediscovery of changed IPs isn’t working as expected?

**Comment by wez** [comment]
It sounds like things are probably working ok for you now. I do want to note that my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) has more flexible and robust networking, so you may wish to consider switching to that.
