### ISSUE TITLE
Device Stops Responding... Reload Integration Fixes It... Temporarily

### ISSUE THREAD

**Issue by superpunkduck** [wez/govee-lan-hass#30]
I have one H6076 enabled with Lan Control....Everything works fine... but after an hour or so... it stops responding in HA.... but if i reload the integration it works again...

Any Idea what is causing the disconnect?

**Comment by LiveForToday** [comment]
Same happens to me. My entire system becomes unresponsive. I have to reboot and then unload the integration or my system just drops off the network, or so it seems. I am running in a container so I wonder if the note about macvlan is perhaps why?

**Comment by superpunkduck** [comment]
[home-assistant_govee_lan_2023-07-16T18-19-09.546Z.log](https://github.com/wez/govee-lan-hass/files/12064768/home-assistant_govee_lan_2023-07-16T18-19-09.546Z.log)

**Comment by wez** [comment]
Are your devices and your hass instance all using static IPs?

**Comment by patrickdronk** [comment]
I'm having the same error. But the weird thing is via homeassistant and homekit it works correctly. But if I try it via node-red I will see this error via the logs..

**Comment by superpunkduck** [comment]
> Are your devices and your hass instance all using static IPs?

They Were not... but i didnt notice the IP change... I just set them to static lease on the router side... ill monitor and check back

**Comment by superpunkduck** [comment]
> Are your devices and your hass instance all using static IPs?

Its already dropping off again... Worked for about 10 minutes... Setting to static changed nothing. I did notice that the MAC address in the logs does not match the MAC in the Govee app... but the IP address ending in .231 has been consistant since i first joined it to the network

**Comment by wez** [comment]
FWIW, while the integration logs device_ids that look like mac addresses, they aren't actual mac addresses.

The `timeout while querying device state` error means that we were waiting for a UDP packet to come back from a device and it didn't arrive in a reasonable time.

UDP is a connectionless protocol which can make troubleshooting it difficult.

In addition, if your hass system has multiple addresses, the kernel can choose to route a UDP send via an unexpected interface, which can cause your govee device to either never receive the packet or to receive it but be unable to route it back to your hass box, perhaps due to firewall rules.

When the integration is started, hass provides a list of valid interfaces and provided that there is just a single entry, the integration will make a point of explicitly setting the source address to that interface.  If you have multiple interfaces, it doesn't know how to reconcile that list (or changes to that list over time!) and this is the kind of issue that might result.

**Comment by superpunkduck** [comment]
> 

So how can i fix this?  Port forwarding?  I dont see any firewall rules.

Im running a Fios G3100 Router

**Comment by wez** [comment]
Sorry to say this, but you'll need to figure out what is happening before anyone can suggest how to resolve it.

It works really well for me here; that suggests that there is something about your environment that is contributing to this.

I suspect that this is somehow related to your network configuration; either on the hass host, or with your router or other network equipment.

**Comment by Viss** [comment]
I'm having this issue as well - i just bought an h6067 stick light / floor lamp, and it just "becomes unavailable". If i reload the integration it comes back to life, but at least a couple times a day in home assistant it just 'becomes unreachable'. No weird networking complexity, everything is on the same lan, HA can see the stick light no problem. I also noticed that when i want to change the colors/brightness/etc sometimes it just 'doesnt respond at all'. 

is there a preferred way to troubleshoot it?

**Comment by Viss** [comment]
I found another quirk - the android app can power the sticklight on and off no probs when home assistant cant find it. I have a unifi wifi system, so i can bump the thing off the network and make it rejoin. From the networking end of things, its visibly on the network, and having it rejoin the network doesnt seem to get home assistant to see it again. The only thing that gets the control of the light back is to 'reload the integration' - and that works every time. 

it seems to be something of a timeout. If i fidget with the light often enough it never 'disappears' - only after a prolonged segment of inactivity, several hours, home assisnant says the light has 'become unavailable'. 

Not sure what reloading the integration is doing to wake it up again, but if theres a way I can script that to just fire once an hour, that would likely fix it

**Comment by Viss** [comment]
I've created a temporary solution to this issue for home assistant.
I made an automation that just reloads the govee integration every hour. 
Here's my code 

```
alias: cron
description: for stuff that needs a cronjob
trigger:
  - platform: time_pattern
    hours: /1
condition: []
action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: 1d7b9c7d6cf4a7d0200378b8c90cbc22
mode: single
```
The entry ID can get fetched out of /root/config/.storage/core.config_entries 
It's a bandaid fix untill this gets patched out in the actual integration code, but it works

**Comment by wez** [comment]
I have no plans to spend time looking at this here in this integration, but I do want to note that my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) is a bit more flexible and robust when it comes to networking, so you may wish to consider moving to that.
