### ISSUE TITLE
Appliances support planned?

### ISSUE THREAD

**Issue by ottes** [wez/govee-lan-hass#31]
Hey,
i'm thinking of forking this + adding all code we need, to controll appliances too. 
Or is this job maybe already done?
My first fan would be H7101.

Will you react to a possible PR and help me integrating this, if i do most of the work here?

regards,
Michael

**Comment by wez** [comment]
Yes, I'd be happy to see a PR for this!  There's more on that in https://github.com/wez/govee-lan-hass/issues/14
I'd like to close this issue as a duplicate of that so that we can centralize the conversation there

**Comment by ottes** [comment]
nice, thanks
