### ISSUE TITLE
H6008 Unsupported Cmd Value,

### ISSUE THREAD

**Issue by Michaelcombs** [wez/govee-lan-hass#33]
The integration finds H6008 bulbs and are available in home assistant. The bulbs turn on and off and display the correct color in home assistant. However, I cannot change the color from home assistant. It causes all bulbs to lose connection temporarily. Waiting a few moments and the bulbs work again. The log is posted below.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/govee_lan/light.py:330
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 9:24:10 PM (13 occurrences)
Last logged: 9:42:43 PM

[139816948107856] failed to control device: Rate limit exceeded, retry in 25 seconds.
[139816948107856] failed to control device: Rate limit exceeded, retry in 30 seconds.
[139816541358544] failed to control device: Unsupported Cmd Value, please check the value of properties.colorTem.range returned by DeviceList
[139816494839056] failed to control device: Rate limit exceeded, retry in 43 seconds.
[139816494839056] failed to control device: Unsupported Cmd Value, please check the value of properties.colorTem.range returned by DeviceList
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 582, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/govee_lan/light.py", line 330, in async_turn_on
    await self._govee_controller.set_color_temperature(
  File "/usr/local/lib/python3.11/site-packages/govee_led_wez/govee.py", line 619, in set_color_temperature
    await asyncio.wait_for(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/govee_led_wez/http.py", line 105, in http_device_control
    raise RuntimeError(f"failed to control device: {message}")
RuntimeError: failed to control device: Rate limit exceeded, retry in 43 seconds.

**Comment by wez** [comment]
The error message makes it sound like you're trying to set a color that is out of the supported range of the device.

Can you manually probe your device capabilities and share the info here?
See: https://github.com/wez/govee-lan-hass/issues/7#issuecomment-1378904151

and also share information about what color/color temperature you were trying to set when you hit that error.

**Comment by Michaelcombs** [comment]
The list devices result is below. I uninstalled and reinstalled after a day and everything worked again. I think the integration stops working because of the rate limit. I may have a device with weak wifi. Could that is trigger a rate limit issue?

As for the colors, I'm using the integrated color picker. 

{
  "data": {
    "devices": [
      {
        "device": "16:BC:D2:39:32:35:1A:38",
        "model": "H7050",
        "deviceName": "Path",
        "controllable": true,
        "retrievable": true,
        "supportCmds": [
          "turn",
          "brightness",
          "color",
          "colorTem"
        ],
        "properties": {
          "colorTem": {
            "range": {
              "min": 2000,
              "max": 9000
            }
          }
        }
      },
      {
        "device": "F7:E1:D4:AD:FC:D0:FE:6E",
        "model": "H6008",
        "deviceName": "Bar 1",
        "controllable": true,
        "retrievable": true,
        "supportCmds": [
          "turn",
          "brightness",
          "color",
          "colorTem"
        ],
        "properties": {
          "colorTem": {
            "range": {
              "min": 2700,
              "max": 6500
            }
          }
        }
      },
      {
        "device": "4E:6F:D4:AD:FC:DB:DC:E2",
        "model": "H6008",
        "deviceName": "Bar 2",
        "controllable": true,
        "retrievable": true,
        "supportCmds": [
          "turn",
          "brightness",
          "color",
          "colorTem"
        ],
        "properties": {
          "colorTem": {
            "range": {
              "min": 2700,
              "max": 6500
            }
          }
        }
      },
      {
        "device": "E5:9F:D4:AD:FC:E8:16:94",
        "model": "H6008",
        "deviceName": "Master 2",
        "controllable": true,
        "retrievable": true,
        "supportCmds": [
          "turn",
          "brightness",
          "color",
          "colorTem"
        ],
        "properties": {
          "colorTem": {
            "range": {
              "min": 2700,
              "max": 6500
            }
          }
        }
      },
      {
        "device": "3F:9D:D4:AD:FC:E8:15:2E",
        "model": "H6008",
        "deviceName": "Master 1",
        "controllable": true,
        "retrievable": true,
        "supportCmds": [
          "turn",
          "brightness",
          "color",
          "colorTem"
        ],
        "properties": {
          "colorTem": {
            "range": {
              "min": 2700,
              "max": 6500
            }
          }
        }
      }
    ]
  },
  "message": "Success",
  "code": 200
}

**Comment by shaggywolfhound** [comment]
I have the roughly the same problem but I am using the mushroom light card. 

Error excerpt:
async_turn_on failed with 'API-Error 400 on command ('name': 'colorTem', 'value': 9000}: {'message": "Unsupported Cmd Value, please check the value of properties.colorTem.range returned by DeviceList" "status":400} for device GoveeDevice (device='44:26:60:74:F4:44:8 model='H6008, device_name=lounge light',.........truncated.

**Comment by wez** [comment]
The reported color temperature range is:

```json
                "properties": {
                    "colorTem": {
                        "range": {
                            "min": 2700,
                            "max": 6500
                        }
                    }
                }
```

but it looks like you are trying to set it to 9000 `'name': 'colorTem', 'value': 9000`, so the device is failing that request.

The easiest thing you can do for now is not try to set it larger than the max.  I do think it would be reasonable to clamp the value to the supported range.

**Comment by wez** [comment]
I think it is something someone could do as a PR to either or both of govee-lan-hass (perhaps there is a way to tell hass about the acceptable range of values) and/or https://github.com/wez/govee-py (where the value could be clamped into range).

I don't currently have time to do either of those things.

**Comment by wez** [comment]
I have no plans to fix that here in this integration, but I do want to note that my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) does handle clamping the color temperature to the range reported by the device so you may wish to consider moving to that.
