### ISSUE TITLE
LAN Connection Issue - Port 4003

### ISSUE THREAD

**Issue by LPirro** [wez/govee-lan-hass#36]
Hi, I'm having some issues configuring LAN access. I have enabled LAN access control in Govee App, but I cannot get the Goovee device in HA via this plugin, also I'm not sure what to do with Port 4003: I should enable this port on my router?

I have home assistant on a docker container and my I have network_mode: host

**Comment by wez** [comment]
I've updated https://github.com/wez/govee-lan-hass/blob/main/README.md#requirements-of-the-lan-api with an improved discussion of the ports
