### ISSUE TITLE
Govee Recessed 4 in Lighting (H601B) Not Showing Up

### ISSUE THREAD

**Issue by jimmykyle** [wez/govee-lan-hass#39]
I added some Govee recessed lighting to my kitchen. The H601A (6 in puck) pulled into Home Assistant no problem but the H601B (4 in puck) does not show up. Any ideas how to get it to?

**Comment by wez** [comment]
The device needs to have the LAN API enabled and be accessible as described in the readme.
I recommend using static IP assignments (eg: via your router's DHCP configuration) to avoid potential issues when DHCP leases expire.

https://github.com/wez/govee-lan-hass#tips-on-enabling-the-lan-api

**Comment by nathang21** [comment]
> The device needs to have the LAN API enabled and be accessible as described in the readme.
> 
> I recommend using static IP assignments (eg: via your router's DHCP configuration) to avoid potential issues when DHCP leases expire.
> 
> 
> 
> https://github.com/wez/govee-lan-hass#tips-on-enabling-the-lan-api 
> 
> 

I have the exact same issue, however both the H601A (6") and H601B (4") unfortunately do not support the LAN API, at least they are not listed on their Support page as supported models.

So in this case Cloud API is only option, but it's interesting only the smaller variant is not picked up. They do show up via the Google Home integration so they do have Cloud API support somehow. The regular hacs-govee integration/repo has the same problem. It is possible support needed to be added on the HA integration side for the B variant?

**Comment by nathang21** [comment]
Does anyone know for specific model support that is missing, should I file an issue with one of the parent dependencies that this Integration uses?

**Comment by jimmykyle** [comment]
I contacted Govee and they said they would be adding the 4 inch to the API in December 2023.

**Comment by nathang21** [comment]
> I contacted Govee and they said they would be adding the 4 inch to the API in December 2023. 

Is that the cloud api or the LAN api (or both?)

I had thought that all their lights were available via the cloud api, and only the LAN api required a firmware update and certain hardware variants on specifically (usually v2) is required.

Either way very exciting I will keep an eye on this!

**Comment by nathang21** [comment]
Update: Govee relaunched their API site, and this model is now listed as supported:
https://developer.govee.com/docs/support-product-model

After an HA restart i'm now seeing them pulled into the official govee integration, but this integration seemed to pull them in automatically via polling (no restart required),

**Comment by wez** [comment]
Sounds like this is good now, so closing!
