### ISSUE TITLE
Brightness problem with H6199

### ISSUE THREAD

**Issue by Juffle74** [wez/govee-lan-hass#4]
Hi,

First thank you very much for all your work on this integration.

Now, I have many Govee lights and one of them, H6199 (Hardware version: 3.02.01 Firmware: 1.09.12) was working fine with an old integration but with this one, if I try to set the brightness with something like "brightness_pct: 75" or "brightness: 192" when calling the light.turn_on service, it show as 100% in the Govee app and the led color flicker randomly like it was a scene but still kind of react to the camera.

If, in the Govee app, I set the brightness back to anything (even 100%), the flickering stop and everything go back to normal.

I did some testing with differents brightness levels and also did try to turn on first then wait a second before setting the brightness but it dosen't change anything.

Any idea?

Home Assistant (blue) 2022.12.8
Supervisor 2022.12.1
Operating System 9.4

Thank you

**Comment by wez** [comment]
Can you try turning on debugging to see if there is anything useful in the logs from both around startup (when the devices are discovered) and around the time you try to change the brightness of the lights?  Putting this in your homeassistant `configuration.yml` and then restarting home assistant will make that take effect:

```yaml
logger:
  logs:
    custom_components.govee_lan: debug
    govee_led_wez: debug
```

If the LAN API is being used, there's not really a lot that could go wrong from the client side, as it is essentially just sending the brightness value directly to the device; it's possible that it is a problem with the implementation of the LAN API on the device itself, in which case reaching out to Govee is probably the thing to do.

I don't have an H6199, but I do have an H610A that got into a similar sounding state once when I was mixing and matching bluetooth control from the govee app (to play with a scene), with subsequent LAN control from an automation in hass.  Power-cycling the device sorted it out for me.

**Comment by Juffle74** [comment]
Hi,

Sorry for the late late reply...

Actually I did change for the T2 and it is working fine.

Thank you

**Comment by wez** [comment]
> Actually I did change for the T2 and it is working fine.

I'm not sure what you mean by this.  Are things working fine for you now?

**Comment by Juffle74** [comment]
Sorry, yes, I had the problem with the Dreamview T1 and since, I've got the T2 and no problem anymore...

Thank you

**Comment by Juffle74** [comment]
Sorry, yes, I had the problem with the Dreamview T1 and since, I've got the T2 and no problem anymore...

Thank you
