### ISSUE TITLE
Segment control?

### ISSUE THREAD

**Issue by Rush** [wez/govee-lan-hass#41]
Can the LAN API via Hass address individual LEDs?

**Comment by Dplein57** [comment]
Pas pour l'instant mais j'espère que cela va être implémenter rapidement... 100:

**Comment by wez** [comment]
No, the documented LAN API does not define a way to address individual leds within a given device.
Reach out to Govee to let them know that you want this functionality.

**Comment by wez** [comment]
Won't be fixed here in this integration, but you can already use it in my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt)

**Comment by Rush** [comment]
I was actually able to code a piece of bluetooth code to control individual LEDs. Unfortunately it wasn't very high frequency, I think at most doing 10Hz so can't do complex animations.
