### ISSUE TITLE
Controlling modes and segments

### ISSUE THREAD

**Issue by Bettiol** [wez/govee-lan-hass#42]
Hello everyone,
I've bought some led strips rgbic goove, but I'm not able to configure modes on goove-lan-hass as I see them in the app and segmented lights. How can I get it working on Home Assistant? I attach a screenshot of the app

Thanks ,

![photo_2023-10-25_18-54-09](https://github.com/wez/govee-lan-hass/assets/36667512/347d7397-f16e-4258-8331-ab61d757d82c)

**Comment by wez** [comment]
The Govee LAN API doesn't provide a documented way to control modes or individual lights, so there is no support for that in this integration.

**Comment by Bettiol** [comment]
Do you know if it is possible to implement this function using the Cloud APIs and not the LAN ones?

**Comment by Joshbloam** [comment]
I have the same limitation. I really wish I could change modes directly from HA.

**Comment by wez** [comment]
I have no plans to fix that here in this integration, but mode control already works in my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt), so you may wish to consider moving to that.
I have plans to also support segmented light control there as well.
