### ISSUE TITLE
Feature: Define devices & ips in config

### ISSUE THREAD

**Issue by the01** [wez/govee-lan-hass#43]
The ability to add devices via config would be very helpful and has been asked for in some other issues (#35, #29).
Even just the ability to define `device id -> IP` mappings would allow users access to the local LAN API in situations where multicast groups are not an option (udp packets sent directly to the device work).

I ended up extending `async_setup_entry()` in `light.py` with my hard coded lan config, but of course this is neither optimal nor will it survive an update of the integration.

**Comment by mediacrave** [comment]
I would love to vote for this feature as well.
I like having an IoT VLAN for these devices and enabling UDP port 4003 from these devices to Home Assistant doesn't seem to be enough to get LAN Mode enabled.

**Comment by wez** [comment]
I've been working on `govee2mqtt`, the successor to `govee-lan-hass`.
It has more extensive options around LAN control; read more about them here:
* https://github.com/wez/govee2mqtt/blob/main/CONFIG.md#lan-api-control 
 
and more about the project in general here: 
* https://github.com/wez/govee2mqtt/tree/main#govee-to-mqtt-bridge-for-home-assistant

**Comment by sdaltons1** [comment]
Hey Wez, thanks for doing this. 

I see the documentation mentions support for the platform api. Does that mean this integration will be able to pull in all govee devices, including appliances, rather than just those with lan api support?

**Comment by wez** [comment]
I'm going to close this issue as I have no plans to fix this here, but you can do this in Govee2MQTT so I'd suggest looking at that.
