### ISSUE TITLE
Address devices in pairs separately?

### ISSUE THREAD

**Issue by zkvvoob** [wez/govee-lan-hass#45]
Hello,

First, thank you for making this integration! I wouldn't have bought a Govee device if it didn't existed.

What I got myself is a H6056 (https://eu.govee.com/collections/tv-gaming-lights/products/govee-rgbicww-wifi-bluetooth-flow-plus-light-bars), which so far works great with Home Assistant. Now, I don't want to look a gift horse in the mouth, but is there a way to control each of the two lights separately (as in, assign different colours to each, for example). I can see that it is possible with the Govee app.

Thanks again!

**Comment by wez** [comment]
No; the LAN protocol doesn't include a documented way to control the interior elements of govee devices

**Comment by zkvvoob** [comment]
Understood. Thank you!
