### ISSUE TITLE
RGB change

### ISSUE THREAD

**Issue by romainpp** [wez/govee-lan-hass#46]
Hello,

first of all, thanks for your work!

The integration in Home assistant is working well but do you know if it possible to change the colour of in the automation mode?

for exemple: to assign to a specific button to turn on the Govee with a certain colour ?

**Comment by wez** [comment]
Seems like a general home assistant question; you'd probably be better served by looking for help in the community forum thingy, perhaps at a post like this https://community.home-assistant.io/t/trigger-automation-with-button-helper-on-dashboard/446816 or by posting there to ask for help
