### ISSUE TITLE
Please add support for H61BE brightness 

### ISSUE THREAD

**Issue by BrenMcGuire-GER** [wez/govee-lan-hass#48]
Hi,

Thanks for this wonderful integration. But I really miss to change the brightness on my H61BE. Changing colors and on/off is no problem. 

Thanks!
Bren

**Comment by wez** [comment]
I have no plans to investigate this here in this integration, but I do want to note that my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) likely already supports this device, so you may wish to consider moving to that.
