### ISSUE TITLE
Integration not showing.

### ISSUE THREAD

**Issue by donster22** [wez/govee-lan-hass#5]
Hi. I've downloaded this via HACS, restarted Home Assistant a number or times, logged out and also cleared my cache but cannot get "Govee LAN Control" to appear in Settings / Devices & Services / ADD INTEGRATION. Any ideas please or more likely to be a fault with my installation?

Home Assistant 2022.9.6
Supervisor 2022.12.1
Operating System 9.3
Frontend 20220907.2 - latest

**Comment by wez** [comment]
please try updating to home assistant 2022.12

**Comment by donster22** [comment]
just completed and it's working. i hadn't realised i was a couple of months out of date. thank you for the prompt and sorry for wasting your time.

**Comment by wez** [comment]
I think there might be something I need to put in the manifest to help with this; thanks for reporting!

**Comment by igorvita** [comment]
Same problem here:
I've downloaded this via HACS, restarted Home Assistant, opened the HACS integrations page, clicked on "Explore & Download Repositories" button, but when i type in "Govee" HA tell me that no repository match with my filter.

My version is the latest:
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

Any help would be very appreciated!
