### ISSUE TITLE
Add explicit switch platform support

### ISSUE THREAD

**Issue by wez** [wez/govee-lan-hass#8]
In https://github.com/wez/govee-lan-hass/issues/7 we discovered that we can pretend that plugs are lights and control them.
We should add a distinct hass switch platform and map those devices to it instead of lights to avoid confusion down the line.
This issue tracks that.

**Comment by gist901** [comment]
Any updates / progress being made on this issue?

**Comment by wez** [comment]
I don't have any devices of this type, and I have no need to work on this any time soon.

**Comment by wez** [comment]
I have no plans to fix that here in this integration, but I do want to note that my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) will create power switches for all device types so you may wish to consider moving to that.
